os: linux
dist: bionic
language: perl
perl:
  - "5.26"

before_install:
  - "sudo apt-get update"
  - "sudo apt-get install -y wget python3 mysql-client"
  - "cpanm --sudo -v --installdeps --notest --cpanfile cpanfile ."

script:
  - "make test_demo_user_scripts"
  - "make clean"

notifications:
  email:
    on_failure: always
