# removed as test_demo depends on too many dependencies
os: linux
dist: focal
language: perl
perl:
  - "5.30"

before_install:
  - "sudo apt-get update"
  - "sudo apt-get install -y wget python3 python3-pip python3-setuptools mysql-client libmysqlclient-dev g++-8 bedtools r-base cpanminus"

before_script:  
  - "make install_REST"
  - "make install_ensembl"
  - "make install_biomart_r"
  - "make install_repeats"

script:
  - "make test"
  - "make test_repeats"

notifications:
  email:
    on_failure: always
