# removed as test_demo depends on too many dependencies
os: linux
dist: focal
language: perl
perl:
  - "5.30"

before_install:
  - "sudo apt-get update"
  - "sudo apt-get install -y wget python3 python3-pip python3-setuptools mysql-client libmysqlclient-dev g++-8 bedtools r-base cpanminus"
  # REST
  - "pip3 install --user requests"
  - "cpanm --sudo -v --installdeps --notest --cpanfile files/cpanfileREST ."
  # Ensembl
  - "cpanm --sudo -v --installdeps --notest --cpanfile files/cpanfileEnsembl ."
  - "cd files"
  - "git clone https://github.com/Ensembl/ensembl.git"
  - "git clone https://github.com/Ensembl/ensembl-variation.git"
  - "git clone https://github.com/Ensembl/ensembl-funcgen.git"
  - "git clone https://github.com/Ensembl/ensembl-compara.git"
  - "git clone https://github.com/Ensembl/ensembl-metadata.git"
  - "git clone -b release-1-6-924 --depth 1 https://github.com/bioperl/bioperl-live.git"
  - "cd .."
  - "make install_repeats"

#before_script:
#  - PERL5LIB=$PWD/ensembl/modules:$PERL5LIB
#  - PERL5LIB=$PWD/ensembl-variation/modules:$PERL5LIB
#  - PERL5LIB=$PWD/ensembl-compara/modules:$PERL5LIB
#  - PERL5LIB=$PWD/ensembl-funcgen/modules:$PERL5LIB
#  - PERL5LIB=$PWD/ensembl-metadata/modules:$PERL5LIB
#  - PERL5LIB=$PWD/bioperl-live:$PERL5LIB
#  - export PERL5LIB

script:
  - "make test"
  - "make test_repeats"

notifications:
  email:
    on_failure: always
