# removed as test_demo depends on too many dependencies
os: linux
dist: bionic
language: perl
perl:
  - "5.26"

before_install:
  - "sudo apt-get update"
  - "sudo apt-get install -y wget python3 mysql-client libmysqlclient-dev"
  - "sudo apt-get install -y r-base
  - "cpanm --sudo -v --installdeps --notest --cpanfile files/cpanfile ."
  - "pip install --user -r files/pythonlist"

before_script:
  # uncomment next line to install biomaRt R package, takes several minutes
  #- "make install"
  - git clone https://github.com/Ensembl/ensembl.git
  - git clone https://github.com/Ensembl/ensembl-variation.git
  - git clone https://github.com/Ensembl/ensembl-funcgen.git
  - git clone https://github.com/Ensembl/ensembl-compara.git
  - git clone https://github.com/Ensembl/ensembl-metadata.git
  - git clone -b release-1-6-924 --depth 1 https://github.com/bioperl/bioperl-live.git
  - PERL5LIB=$PWD/ensembl/modules:$PERL5LIB
  - PERL5LIB=$PWD/ensembl-variation/modules:$PERL5LIB
  - PERL5LIB=$PWD/ensembl-compara/modules:$PERL5LIB
  - PERL5LIB=$PWD/ensembl-funcgen/modules:$PERL5LIB
  - PERL5LIB=$PWD/ensembl-metadata/modules:$PERL5LIB
  - PERL5LIB=$PWD/bioperl-live:$PERL5LIB
  - export PERL5LIB

script:
  - "make test"

notifications:
  email:
    on_failure: always
