# removed as test_demo depends on too many dependencies
os: linux
dist: bionic
language: perl
perl:
  - "5.26"

before_install:
  - "sudo apt-get update"
  - "sudo apt-get install -y wget r-base python3 mysql-client libmysqlclient-dev"
  - "cpanm --sudo -v --installdeps --notest --cpanfile cpanfile ."

before_script:
  - "make install"
  # http://plants.ensembl.org/info/docs/api/api_installation.html
  - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl.git
  - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-compara.git
  - git clone -b release-1-6-924 --depth 1 https://github.com/bioperl/bioperl-live.git
  - PERL5LIB=$PWD/ensembl:$PERL5LIB
  - PERL5LIB=$PWD/ensembl-compara:$PERL5LIB
  - PERL5LIB=$PWD/bioperl-live:$PERL5LIB
  - export PERL5LIB

script:
  - "make test"

notifications:
  email:
    on_failure: always
